name: PublicManual2

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Choose deployment target'
        required: true
        default: 'stg'
        type: choice
        options:
          - stg
          - prd
          - all
      confirm:
        description: 'Confirm deployment (yes/no)'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

jobs:
  stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.target == 'stg' || github.event.inputs.target == 'all' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging
        run: echo "Deploying to Staging..."

  prd:
    environment: manual
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: echo "Deploying to Production..."
